### ISSUE TITLE
[1414]App crashing

### ISSUE THREAD

**Issue by RonakLakhotia** [CATcher-org/pe-evaluation#1]
<img alt="screen shot 2018-11-16 at 8 20 00 pm" width="1062" src="https://user-images.githubusercontent.com/42432423/48621044-41748680-e9dd-11e8-94a4-01811f1fa9c6.png">

It is able to change the root password. So once someone log in through root user account, after he or she change this passwoard The other users who have not register yet cannot access ever agian.
[original: nus-cs2103-AY1819S1/pe#1378]
**Comment by `NightYeti`**
Hi.

Ability to change root password is a feature, not a bug.

Typically, the owner of the application (perhaps manager of the wedding planning agency) holds the root account. He can decides to change his root account at any point in time (for example, if he feels that his account has been compromised). He will register the account for his employees and assign them account role (either super user, or read only user) accordingly. The employees can then change their own password later.

> The other users who have not register yet cannot access ever agian.

The above quote is not true as users do not simply register for their account individually. The users of this app is wedding planning agency. So employees of wedding planning agency will get their account from their employer.

[original: [nus-cs2103-AY1819S1/pe-results#1414](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/1414)]
proposed-assignees: `dongsiji`, `nightyeti`, `liaujianjie`, `wailunlim`, `eehooi`,

**Tutor to check:**

* [x]  justification for rejection

**Comment by testathorTutor** [comment]
## Tutor's Response
ss
## State the duplicated issue here, if any\n-

**Comment by testathorTutor** [comment]
## Tutor's Response
ss
## State the duplicated issue here, if any\nDuplicate of #2

**Comment by testathorTutor** [comment]
## Tutor's Response
f
## State the duplicated issue here, if any\nDuplicate of #2

**Comment by testathorTutor** [comment]
## Tutor's Response
acscs
## State the duplicated issue here, if any\n-

**Comment by testathorTutor** [comment]
## Tutor's Response
k
## State the duplicated issue here, if any\n-

**Comment by testathorTutor** [comment]
## Tutor's Response
s
## State the duplicated issue here, if any\n-

**Comment by testathorTutor** [comment]
## Tutor's Response
aa


## State the duplicated issue here, if any
null
