### ISSUE TITLE
New Moderation issue template (New response)

### ISSUE THREAD

**Issue by KevinCJH** [CATcher-org/pe-evaluation#10]
# Description
{original issue description}
# Team's Response
{team's response}
 # Disputes

### Team says:
Yes, we missed this. But it's a minor bug.

### Tester says:
I think it should be medium. Most users are affected.

-------------------
### Team says:
This is a documentation bug!

### Tester says:
Nope it affects the url, so its a functionality bug.

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Downgrade of severity

- [x] Done

This is justified.

-------------------
## :question: Change of type

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Downgrade of severity

- [x] Done

test

-------------------
## :question: Change of type

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Downgrade of severity

- [x] Done

test

-------------------
## :question: Change of type

- [x] Done

test 2

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Downgrade of severity

- [x] Done

test1

-------------------
## :question: Change of type

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [x] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [x] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [x] Done

[replace this with your explanation]

-------------------
