### ISSUE TITLE
Test pending

### ISSUE THREAD

**Issue by KevinCJH** [CATcher-org/pe-evaluation#11]
# Description
{original issue description}
# Team's Response
{team's response}
 # Disputes

### Team says:
Yes, we missed this. But it's a minor bug.

### Tester says:
I think it should be medium. Most users are affected.

-------------------
### Team says:
This is a documentation bug!

### Tester says:
Nope it affects the url,aaaaa

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Downgrade of severity

- [x] Done

Test done

-------------------
## :question: Change of type

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
place holder

**Comment by KevinCJH** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

Done already

-------------------
## :question: Issue type

- [x] Done

Test

-------------------
