### ISSUE TITLE
Test new1

### ISSUE THREAD

**Issue by KevinCJH** [CATcher-org/pe-evaluation#12]
# Description
{original issue description}
# Team's Response
{team's response}
 # Disputes

### Team says:
Yes, we missed this. But it's a minor bug.

### Tester says:
I think it should be medium. Most users are affected.

-------------------
### Team says:
This is a documentation bug!

### Tester says:
Nope it affects the url, so its a functionality bug.

-------------------
### Team says:
This is a test

### Tester says:
This is a test

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Downgrade of severity

- [x] Done

test done

-------------------
## :question: Change of type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Testing stuff

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

tets



-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

asdad



-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [x] Done

111


-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [x] Done

1111


-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [x] Done

1111


-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [x] Done

1111


-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [x] Done

aa


-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [x] Done

ddd


-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation
## :question: Issue severity

- [x] Done

aaaavvvdddccccddd

1111


-------------------
## :question: Issue type

- [x] Done

ccc1


-------------------
## :question: Issue test

- [x] Done

ddd

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation
## :question: Issue severity

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue type

- [x] Done

3213


-------------------
## :question: Issue test

- [x] Done

dasdad


-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation
## :question: Issue severity

- [ ] Done

abc

-------------------
## :question: Issue type

- [x] Done

ccc1

-------------------
## :question: Issue test

- [x] Done

aaa222


-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation
## :question: Issue severity

- [ ] Done

abc

-------------------
## :question: Issue type

- [x] Done

ccc1

-------------------
## :question: Issue test

- [x] Done

aaa222


-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

tasd

-------------------
## :question: Issue type

- [x] Done

sdasdas

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

tasd

-------------------
## :question: Issue type

- [x] Done

sdasdas

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

tasd

-------------------
## :question: Issue type

- [x] Done

sdasdas

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

tasd

-------------------
## :question: Issue type

- [x] Done

sdasdas

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by JunWei96** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

tasd

-------------------
## :question: Issue type

- [x] Done

sdasdas

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

tasd333


-------------------
## :question: Issue type

- [x] Done

sdasdas

-------------------
## :question: Issue test

- [ ] Done

[replace this with your explanation]

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

asdasd123


-------------------
## :question: Issue type

- [ ] Done

[replace this with your explanation]

-------------------
## :question: Issue test

- [x] Done

adasdsa1222


-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

asdasd123

-------------------
## :question: Issue type

- [x] Done

21321321


-------------------
## :question: Issue test

- [x] Done

adasdsa1222

-------------------

**Comment by testathorTutor** [comment]
# Team's Response
{team's response}
 ## Duplicate status (if any):
--

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

I agree with tester.


-------------------
## :question: Issue type

- [x] Done

I agree with tester.


-------------------
## :question: Issue test

- [x] Done

I agree with tester.


-------------------
