### ISSUE TITLE
Test new 2

### ISSUE THREAD

**Issue by KevinCJH** [CATcher-org/pe-evaluation#13]
# Description
{original issue description}
# Team's Response
{team's response}
 # Disputes

### Team says:
Yes, we missed this. But it's a minor bug.

### Tester says:
I think it should be medium. Most users are affected.

-------------------
### Team says:
This is a documentation bug!

### Tester says:
Nope it affects the url, so its a functionality bug.

-------------------
### Team says:
This is a test

### Tester says:
This is a test

-------------------

**Comment by testathorTutor** [comment]
stray comment

**Comment by KevinCJH** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

Not done yet...
\\\\

-------------------
## :question: Issue type

- [x] Done

Correct

-------------------
## :question: Issue test

- [x] Done

Wrong

-------------------
