### ISSUE TITLE
aaaaaaaaa

### ISSUE THREAD

**Issue by KevinCJH** [CATcher-org/pe-evaluation#17]
# Description
{original issue description}
# Team's Response
{team's response}
 # Disputes

### Team says:
Yes, we missed this. But it's a minor bug.

### Tester says:
I think it should be high. Most users are affected by this big issue.

-------------------

**Comment by KevinCJH** [comment]
stray comment 17

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

why candnjannawnaadawdw

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

bbbbbbbb

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [x] Done

aaaaaa

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

slflknerg

-------------------

**Comment by testathorTutor** [comment]
# Tutor Moderation

## :question: Issue severity

- [ ] Done

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

-------------------
