### ISSUE TITLE
Check again test (Old template)

### ISSUE THREAD

**Issue by RonakLakhotia** [CATcher-org/pe-evaluation#3]
# Description
I can't log in!
# Team's Response
Hi.

Because you have not signed up.
[original: nus-cs2103-AY1819S1/pe-results#1414]
 # Disputes

**Comment by testathorTutor** [comment]
## Tutor's Response
ssaaa
## State the duplicated issue here, if any

**Comment by testathorTutor** [comment]
## Tutor's Response
sd
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment]
## Tutor's Response
aa
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment]
## Tutor's Response
test
## State the duplicated issue here, if any
Duplicate of #5

**Comment by testathorTutor** [comment]
## Tutor's Response
test






## State the duplicated issue here, if any
--
